# Generated by Django 4.1.1 on 2022-09-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='사용자 이름')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='배송지')),
                ('type', models.CharField(blank=True, choices=[('manager', '관리자'), ('general', '사용자')], default='general', max_length=10, verbose_name='사용자 유형')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
